### ISSUE TITLE
Name Attribute of @CompositeQueryIndex Annotation is ignored

### ISSUE THREAD

**Issue by mspoeri** [spring-projects/spring-data-couchbase#1190]
Defining the name Attribute in the `@CompositeQueryIndex` annotation is ignored when the index is created on server start.

This causes problems if one of the specified index fields is a nested field since this causes a `com.couchbase.client.core.error.ParsingFailureException`.

`Caused by: org.springframework.dao.DataIntegrityViolationException: Could not auto-create index with statement: CREATE INDEX idx_couchbaseTrackingReport_javaclass_internalobjects.timestamp ON `tracking` (javaClass,internalObjects.timeStamp) WHERE `javaClass` = "de.itscope.platform.trackingservice.model.couchbase.CouchbaseTrackingReport"; nested exception is com.couchbase.client.core.error.ParsingFailureException: Parsing of the input failed {"completed":true,"coreId":"0x238db32a00000001","errors":[{"code":3000,"message":"syntax error - at ."}],"idempotent":false,"lastDispatchedFrom":"192.168.1.96:60953","lastDispatchedTo":"couchbase.platform.staging.local.itscope.com:8093","requestId":11,"requestType":"QueryRequest","retried":0,"service":{"operationId":"700abc53-988f-4f07-bba8-0cc5f3a5c942","statement":"CREATE INDEX idx_couchbaseTrackingReport_javaclass_internalobjects.timestamp ON `tracking` (javaClass,internalObjects.timeStamp) WHERE `javaClass` = \"de.itscope.platform.trackingservice.model.couchbase.CouchbaseTrackingReport\"","type":"query"},"timeoutMs":75000,"timings":{"dispatchMicros":2186,"totalDispatchMicros":2186,"totalMicros":3592}}
	at org.springframework.data.couchbase.core.index.CouchbasePersistentEntityIndexCreator.createIndex(CouchbasePersistentEntityIndexCreator.java:112)
	at org.springframework.data.couchbase.core.index.CouchbasePersistentEntityIndexCreator.checkForAndCreateIndexes(CouchbasePersistentEntityIndexCreator.java:90)
	at org.springframework.data.couchbase.core.index.CouchbasePersistentEntityIndexCreator.checkForIndexes(CouchbasePersistentEntityIndexCreator.java:77)
	at org.springframework.data.couchbase.core.index.CouchbasePersistentEntityIndexCreator.onApplicationEvent(CouchbasePersistentEntityIndexCreator.java:63)
	at org.springframework.data.couchbase.core.index.CouchbasePersistentEntityIndexCreator.onApplicationEvent(CouchbasePersistentEntityIndexCreator.java:37)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:421)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:378)
	at org.springframework.data.mapping.context.AbstractMappingContext.addPersistentEntity(AbstractMappingContext.java:375)
	at org.springframework.data.couchbase.core.mapping.CouchbaseMappingContext.addPersistentEntity(CouchbaseMappingContext.java:139)
	at org.springframework.data.couchbase.core.mapping.CouchbaseMappingContext.getPersistentEntity(CouchbaseMappingContext.java:159)
	at org.springframework.data.couchbase.core.mapping.CouchbaseMappingContext.getPersistentEntity(CouchbaseMappingContext.java:41)
	at org.springframework.data.mapping.context.AbstractMappingContext.getPersistentEntity(AbstractMappingContext.java:201)
	at org.springframework.data.mapping.context.AbstractMappingContext.getPersistentEntity(AbstractMappingContext.java:87)
	at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.lambda$afterPropertiesSet$6(RepositoryFactoryBeanSupport.java:326)
	at java.base/java.util.Optional.ifPresent(Optional.java:176)
	at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.afterPropertiesSet(RepositoryFactoryBeanSupport.java:326)
	at org.springframework.data.couchbase.repository.support.ReactiveCouchbaseRepositoryFactoryBean.afterPropertiesSet(ReactiveCouchbaseRepositoryFactoryBean.java:89)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1845)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1782)
	... 72 more
Caused by: com.couchbase.client.core.error.ParsingFailureException: Parsing of the input failed {"completed":true,"coreId":"0x238db32a00000001","errors":[{"code":3000,"message":"syntax error - at ."}],"idempotent":false,"lastDispatchedFrom":"192.168.1.96:60953","lastDispatchedTo":"couchbase.platform.staging.local.itscope.com:8093","requestId":11,"requestType":"QueryRequest","retried":0,"service":{"operationId":"700abc53-988f-4f07-bba8-0cc5f3a5c942","statement":"CREATE INDEX idx_couchbaseTrackingReport_javaclass_internalobjects.timestamp ON `tracking` (javaClass,internalObjects.timeStamp) WHERE `javaClass` = \"de.itscope.platform.trackingservice.model.couchbase.CouchbaseTrackingReport\"","type":"query"},"timeoutMs":75000,"timings":{"dispatchMicros":2186,"totalDispatchMicros":2186,"totalMicros":3592}}
	at com.couchbase.client.java.AsyncUtils.block(AsyncUtils.java:51)
	at com.couchbase.client.java.Cluster.query(Cluster.java:393)
	at com.couchbase.client.java.Cluster.query(Cluster.java:380)
	at org.springframework.data.couchbase.core.index.CouchbasePersistentEntityIndexCreator.createIndex(CouchbasePersistentEntityIndexCreator.java:107)
	... 93 more
	Suppressed: java.lang.Exception: The above exception was originally thrown by another thread at the following location.
		at com.couchbase.client.core.io.netty.query.QueryChunkResponseParser.errorsToThrowable(QueryChunkResponseParser.java:131)
		at java.base/java.util.Optional.map(Optional.java:258)
		at com.couchbase.client.core.io.netty.query.QueryChunkResponseParser.error(QueryChunkResponseParser.java:118)
		at com.couchbase.client.core.io.netty.chunk.ChunkedMessageHandler.lambda$maybeCompleteResponseWithFailure$1(ChunkedMessageHandler.java:281)
		at java.base/java.util.Optional.orElseGet(Optional.java:362)
		at com.couchbase.client.core.io.netty.chunk.ChunkedMessageHandler.maybeCompleteResponseWithFailure(ChunkedMessageHandler.java:280)
		at com.couchbase.client.core.io.netty.chunk.ChunkedMessageHandler.channelRead(ChunkedMessageHandler.java:212)
		at com.couchbase.client.core.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
		at com.couchbase.client.core.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
		at com.couchbase.client.core.deps.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
		at com.couchbase.client.core.deps.io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
		at com.couchbase.client.core.deps.io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
		at com.couchbase.client.core.deps.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
		at com.couchbase.client.core.deps.io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
		at com.couchbase.client.core.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
		at com.couchbase.client.core.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
		at com.couchbase.client.core.deps.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
		at com.couchbase.client.core.deps.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
		at com.couchbase.client.core.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
		at com.couchbase.client.core.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
		at com.couchbase.client.core.deps.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
		at com.couchbase.client.core.deps.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
		at com.couchbase.client.core.deps.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
		at com.couchbase.client.core.deps.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
		at com.couchbase.client.core.deps.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
		at com.couchbase.client.core.deps.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
		at com.couchbase.client.core.deps.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
		at com.couchbase.client.core.deps.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
		at com.couchbase.client.core.deps.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
		at java.base/java.lang.Thread.run(Thread.java:832)
`

**Comment by mikereiche** [comment]
Thanks for opening this issue.  It was just fixed and is in 4.2.4 which was released 2021-08-12
https://github.com/spring-projects/spring-data-couchbase/commit/e0b68739205fcf18b245f0979c79d988b851f2a6

https://github.com/spring-projects/spring-data-couchbase/issues/1166
