### ISSUE TITLE
count() methods fail with JDK 16

### ISSUE THREAD

**Issue by mikereiche** [spring-projects/spring-data-couchbase#1228]
java.lang.reflect.InaccessibleObjectException: Unable to make field private final long java.lang.Long.value accessible: module java.base does not "opens java.lang" to unnamed module @2d6d8735

	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:177)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:171)
	at org.springframework.util.ReflectionUtils.makeAccessible(ReflectionUtils.java:787)
	at org.springframework.data.mapping.context.AbstractMappingContext$PersistentPropertyCreator.doWith(AbstractMappingContext.java:531)
	at org.springframework.util.ReflectionUtils.doWithFields(ReflectionUtils.java:710)
	at org.springframework.data.mapping.context.AbstractMappingContext.doAddPersistentEntity(AbstractMappingContext.java:408)
	at org.springframework.data.mapping.context.AbstractMappingContext.addPersistentEntity(AbstractMappingContext.java:372)
	at org.springframework.data.couchbase.core.mapping.CouchbaseMappingContext.addPersistentEntity(CouchbaseMappingContext.java:139)
	at org.springframework.data.couchbase.core.mapping.CouchbaseMappingContext.getPersistentEntity(CouchbaseMappingContext.java:159)
	at org.springframework.data.couchbase.core.mapping.CouchbaseMappingContext.getPersistentEntity(CouchbaseMappingContext.java:41)
	at org.springframework.data.mapping.context.AbstractMappingContext.getPersistentEntity(AbstractMappingContext.java:208)
	at org.springframework.data.mapping.context.AbstractMappingContext.getPersistentEntity(AbstractMappingContext.java:91)
	at org.springframework.data.couchbase.repository.query.StringBasedN1qlQueryParser.getProjectedFields(StringBasedN1qlQueryParser.java:197)
	at org.springframework.data.couchbase.repository.query.StringBasedN1qlQueryParser.createN1qlSpelValues(StringBasedN1qlQueryParser.java:164)
	at org.springframework.data.couchbase.repository.query.StringBasedN1qlQueryParser.<init>(StringBasedN1qlQueryParser.java:153)
	at org.springframework.data.couchbase.core.query.Query.getN1qlSpelValues(Query.java:367)
	at org.springframework.data.couchbase.core.query.Query.toN1qlSelectString(Query.java:328)
	at org.springframework.data.couchbase.core.ReactiveFindByQueryOperationSupport$ReactiveFindByQuerySupport.assembleEntityQuery(ReactiveFindByQueryOperationSupport.java:240)
	at org.springframework.data.couchbase.core.ReactiveFindByQueryOperationSupport$ReactiveFindByQuerySupport.count(ReactiveFindByQueryOperationSupport.java:217)

**Comment by mikereiche** [comment]
This might have started when the project() api was added and the corresponding .as(returnType) were added to AbstractCouchbaseQuery

**Comment by mikereiche** [comment]
This looks like it is fixed in https://github.com/spring-projects/spring-data-couchbase/issues/1278
