### ISSUE TITLE
How to retrieve aggregate result with Spring repository with @Query

### ISSUE THREAD

**Issue by JesusTheHun** [spring-projects/spring-data-couchbase#1367]
Things have moved a lot regarding queries lately so I'm wondering when it will be possible to do something as simple as this :

```java
class MyRepo extends Repository {
    @Query("SELECT RAW ARRAY_AGG(myArrayField) ...")
    List<String> getMyData();
}
```

It is a real PITA to not be able to do that and have to add useless templating to workaround this.
Add a new annotations like `@AggregateQuery` and/or `@RawQuery` if you need 🤷‍♂️

**Comment by mikereiche** [comment]
Maybe I don't understand the question, but if your method is defined to return a list, and your sql returns a list of that type - that's what you'll get.

```
	@Query("select \"\" as __id, 0 as __cas, iata from #{#n1ql.bucket} where iata is valued order by iata" )
	List<String> getAllIata();

	result: [vie, xxx]
	
	@Test
	void shouldRetrieveArray() {
		Airport vie = null;
		Airport xxx = null;
		try {
			vie = new Airport("airports::vie", "vie", "low4");
			xxx = new Airport("airports::xxx", "xxx", "xxx148");
			airportRepository.save(vie);
			airportRepository.save(xxx);
			java.util.Collection<String> all = new ArrayList<>();
			airportRepository.getAllIata().forEach(all::add);
			assertFalse(all.isEmpty());
			assertEquals(2,all.size());
			System.out.println("result: "+all);
			assertTrue( all.contains(vie.getIata()) && all.contains(xxx.getIata()) );
		} finally {
			airportRepository.delete(vie);
			airportRepository.delete(xxx);
		}
	}
	
```

**Comment by mikereiche** [comment]
If instead you want each result to contain an array that is constructed in the projection (which is more like your example), then it will need a custom converter as the spring data framework doesn't seem to support that.

	@Query("select \"\" as __id, 0 as __cas, [ iata, icao] from #{#n1ql.bucket} where iata is valued" )
	List<String[]> getAllIataAndIcao();
	
	org.springframework.core.convert.ConversionFailedException: Failed to convert from type [java.util.ArrayList<?>] to type [@org.springframework.data.couchbase.repository.ScanConsistency @org.springframework.data.couchbase.repository.Query java.util.List<java.lang.String[]>] for value '[CouchbaseList{payload=[vie, low4]}, CouchbaseList{payload=[xxx, xxx148]}]'; nested exception is org.springframework.core.convert.ConverterNotFoundException: No converter found capable of converting from type [org.springframework.data.couchbase.core.mapping.CouchbaseList] to type [@org.springframework.data.couchbase.repository.ScanConsistency @org.springframework.data.couchbase.repository.Query java.lang.String[]]

	at org.springframework.core.convert.support.ConversionUtils.invokeConverter(ConversionUtils.java:47)
	at org.springframework.core.convert.support.GenericConversionService.convert(GenericConversionService.java:192)
	at org.springframework.core.convert.support.GenericConversionService.convert(GenericConversionService.java:213)
	at org.springframework.data.repository.core.support.QueryExecutionResultHandler.postProcessInvocationResult(QueryExecutionResultHandler.java:167)
	at org.springframework.data.repository.core.support.QueryExecutionResultHandler.postProcessInvocationResult(QueryExecutionResultHandler.java:77)

**Comment by mikereiche** [comment]
If you were wanting to return an array in each row, like this.  A custom converter is required as the spring framework doesn't automatically handle that.
```

	@Query("select \"\" as __id, 0 as __cas, [ iata, icao] from #{#n1ql.bucket} where iata is valued" )
	List<String[]> getAllIata();

org.springframework.core.convert.ConversionFailedException: Failed to convert from type [java.util.ArrayList<?>] to type [@org.springframework.data.couchbase.repository.ScanConsistency @org.springframework.data.couchbase.repository.Query java.util.List<java.lang.String[]>] for value '[CouchbaseList{payload=[vie, low4]}, CouchbaseList{payload=[xxx, xxx148]}]'; nested exception is org.springframework.core.convert.ConverterNotFoundException: No converter found capable of converting from type [org.springframework.data.couchbase.core.mapping.CouchbaseList] to type [@org.springframework.data.couchbase.repository.ScanConsistency @org.springframework.data.couchbase.repository.Query java.lang.String[]]
 
                at org.springframework.core.convert.support.ConversionUtils.invokeConverter(ConversionUtils.java:47)
                at org.springframework.core.convert.support.GenericConversionService.convert(GenericConversionService.java:192)
                at org.springframework.core.convert.support.GenericConversionService.convert(GenericConversionService.java:213)
                at org.springframework.data.repository.core.support.QueryExecutionResultHandler.postProcessInvocationResult(QueryExecutionResultHandler.java:167)
                at org.springframework.data.repository.core.support.QueryExecutionResultHandler.postProcessInvocationResult(QueryExecutionResultHandler.java:77)
```
