### ISSUE TITLE
Collection not being reachable when call a custom query inside a @Transactional method (Spring-Data-Couchbase 5.0.0-M6)

### ISSUE THREAD

**Issue by PRodrigues-eb** [spring-projects/spring-data-couchbase#1569]
On our repository classes we have the following query methods:

```
public interface AccountRepository extends CouchbaseRepository<ClientOperationsAccount, String> {

    Optional<ClientOperationsAccount> findBySalesforceId(String salesforceId);
    
    Optional<ClientOperationsAccount> findByEnterpriseAccountId(String enterpriseAccountId);
}
```

If we call any of them outside a @Transactional method it works well, but if it be called inside a @Transactional method we got the following error:

`Keyspace not found in CB datastore: default:client-operations-account - cause: No bucket named client-operations-account
`

Seems that it's not pointing to the configured bucket and scope when it is called inside a @Transactional method, interestingly it only happen to custom query methods.

Exception:

```
Caused by: org.springframework.data.couchbase.transaction.error.TransactionSystemUnambiguousException: Transaction has failed with cause 'com.couchbase.client.core.error.IndexFailureException: The server reported an issue with the underlying index {"completed":true,"coreId":"0xb8671a600000001","errors":[{"code":12003,"message":"Keyspace not found in CB datastore: default:client-operations-account - cause: No bucket named client-operations-account","retry":false}],"httpStatus":500,"idempotent":false,"lastDispatchedFrom":"127.0.0.1:56741","lastDispatchedTo":"localhost:8093","requestId":124,"requestType":"QueryRequest","retried":0,"service":{"operationId":"query","statement":"SELECT `_class`, META(`client-operations-account`).`id` AS __id, `enterpriseAccountId`, `salesforceId`, `bullhornId`, `accountName`, `businessType`, `currentServiceLevel`, `accountDescription`, `industry`, `inheritedAccount`, `invoiceName`, `accountActivatedDate`, `legacyId`, `accountParentId`, `website`, `wmbeAccount`, `shippingAddress`, `accountBranch`, `accountBrand`, `accountFinancials`, `accountSetup`, `brandSpecificRollups`, META(`client-operations-account`).`cas` AS __cas, `createdAt`, `updatedAt`, `createdBy`, `updatedBy` FROM `client-operations-account` WHERE `_class` = \"com.employbridge.account.manager.model.ClientOperationsAccount\" AND `enterpriseAccountId` = $1","target":"NodeIdentifier{address=localhost, managerPort=8091}","type":"query"},"timeoutMs":25993,"timings":{"dispatchMicros":54512,"totalDispatchMicros":54512,"totalMicros":55329}}'
	at org.springframework.data.couchbase.transaction.CouchbaseCallbackTransactionManager.convert(CouchbaseCallbackTransactionManager.java:139)
	at org.springframework.data.couchbase.transaction.CouchbaseCallbackTransactionManager.executeNewTransaction(CouchbaseCallbackTransactionManager.java:130)
	at org.springframework.data.couchbase.transaction.CouchbaseCallbackTransactionManager.execute(CouchbaseCallbackTransactionManager.java:83)
	at org.springframework.data.couchbase.transaction.CouchbaseTransactionInterceptor.invokeWithinTransaction(CouchbaseTransactionInterceptor.java:81)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:755)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:706)
	at com.employbridge.account.manager.service.impl.ClientOperationsAccountServiceImpl$$SpringCGLIB$$0.update(<generated>)
	at com.employbridge.account.manager.kafka.SalesforceAccountListener.tryToUpdateAccount(SalesforceAccountListener.java:146)
	... 55 common frames omitted
```

**Comment by mikereiche** [comment]
> Seems that it's not pointing to the configured bucket and scope

How is the bucket being configured?
How is the scope being configured?
Please show the code that makes the calls.

**Comment by maleficuss** [comment]
Hi,  same problem happens for reactive repositories

**Comment by mikereiche** [comment]
@maleficuss - in what version? There fix was in the ReactiveOperation (which is called by the non-reactive operation).

**Comment by maleficuss** [comment]
@mikereiche sorry for resurrecting old post, when i saw the same case that i have i didnt even check date of the post :)

Im using 5.0.4

**Comment by mikereiche** [comment]
Ok - I think I just fixed this in https://github.com/spring-projects/spring-data-couchbase/issues/1745

**Comment by maleficuss** [comment]
@mikereiche thank you, I'm gonna try with that :)
