### ISSUE TITLE
fix project so that intellij recognizes modules

### ISSUE THREAD

**Issue by mikereiche** [spring-projects/spring-data-couchbase#1572]
After splitting spring-data-couchbase into spring-data-couchbase/spring-data-couchbase, spring-data-couchbase/spring-data-testapp and spring-data-couchbase/spring-data-couchbase-distribution,  [ edit - see below for simpler work-around] intellij-idea doesn't recognize them as modules until one creates a dummy module and then deletes it.    Intellij says that deleting the mvnw and mvnw.cmd scripts will solve the problem - but that doesn't help.

https://youtrack.jetbrains.com/issue/IDEA-299212

**Comment by mikereiche** [comment]
Seems the necessary fix is to rename spring-data-couchbase/spring-data-couchbase to spring-data-couchbase/spring-data-couchbase-main to avoid the conflict.

I also noticed that having the same name results in : 

com.intellij.diagnostic.PluginException: Cannot create class CompareDependencies (classloader=PluginClassLoader(plugin=PluginDescriptor(name=Maven Dependency Manager, id=Maven Dependency Manager, descriptorPath=plugin.xml, path=~/Library/Application Support/JetBrains/IntelliJIdea2022.2/plugins/MavenDependencyPlugin, version=1.02, package=null, isBundled=false), packagePrefix=null, instanceId=194, state=active))
                at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:883)
                at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:900)
                at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.instantiate(ActionManagerImpl.java:201)
                at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.convertStub(ActionManagerImpl.java:186)
                at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getActionImpl(ActionManagerImpl.java:527)
                at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getAction(ActionManagerImpl.java:516)
                at com.intellij.openapi.actionSystem.DefaultActionGroup.unStub(DefaultActionGroup.java:409)
                at com.intellij.openapi.actionSystem.DefaultActionGroup.getChildren(DefaultActionGroup.java:365)
                at com.intellij.openapi.actionSystem.ActionGroupStub.initGroup(ActionGroupStub.kt:34)
                at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.convertGroupStub(ActionManagerImpl.java:240)
                at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getActionImpl(ActionManagerImpl.java:527)
                at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getAction(ActionManagerImpl.java:516)
                at com.intellij.openapi.actionSystem.DefaultActionGroup.unStub(DefaultActionGroup.java:409)
                at com.intellij.openapi.actionSystem.DefaultActionGroup.getChildren(DefaultActionGroup.java:365)
                at com.intellij.openapi.actionSystem.DefaultActionGroup.getChildren(DefaultActionGroup.java:343)
                at com.intellij.ide.ui.customization.CustomizationUtil.getReordableChildren(CustomizationUtil.java:92)
                at com.intellij.ide.ui.customization.CustomisedActionGroup.getChildren(CustomisedActionGroup.java:44)
                at com.intellij.openapi.wm.impl.IdeMenuBar.expandActionGroup(IdeMenuBar.java:509)
                at com.intellij.openapi.wm.impl.IdeMenuBar.doUpdateMenuActions(IdeMenuBar.java:406)
                at com.intellij.openapi.wm.impl.IdeMenuBar.lambda$addNotify$4(IdeMenuBar.java:286)
                at com.intellij.openapi.actionSystem.ex.ActionManagerEx.doWithLazyActionManager(ActionManagerEx.java:114)
                at com.intellij.openapi.wm.impl.IdeMenuBar.addNotify(IdeMenuBar.java:284)
                at java.desktop/java.awt.Container.addNotify(Container.java:2804)
                at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4847)
                at java.desktop/java.awt.Container.addNotify(Container.java:2804)
                at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4847)
                at java.desktop/javax.swing.JRootPane.addNotify(JRootPane.java:729)
                at com.intellij.openapi.wm.impl.IdeRootPane.addNotify(IdeRootPane.java:208)
                at java.desktop/java.awt.Container.addNotify(Container.java:2804)
                at java.desktop/java.awt.Window.addNotify(Window.java:797)
                at java.desktop/java.awt.Frame.addNotify(Frame.java:495)
                at com.intellij.openapi.wm.impl.IdeFrameImpl.addNotify(IdeFrameImpl.java:76)
                at java.desktop/java.awt.Window.show(Window.java:1059)
                at com.intellij.openapi.wm.impl.IdeFrameImpl.show(IdeFrameImpl.java:136)
                at java.desktop/java.awt.Component.show(Component.java:1749)
                at java.desktop/java.awt.Component.setVisible(Component.java:1696)
                at java.desktop/java.awt.Window.setVisible(Window.java:1042)
                at com.intellij.openapi.project.impl.DefaultProjectUiFrameManager.doInit(ProjectFrameAllocator.kt:320)
                at com.intellij.openapi.project.impl.DefaultProjectUiFrameManager.access$doInit(ProjectFrameAllocator.kt:282)
                at com.intellij.openapi.project.impl.DefaultProjectUiFrameManager$init$1.run(ProjectFrameAllocator.kt:299)
                at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
                at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
                at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
                at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
                at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:513)
                at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:75)
                at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:118)
                at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:42)
                at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
                at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:779)
                at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
                at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
                at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
                at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
                at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:749)
                at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:898)
                at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:746)
                at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:439)
                at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:791)
                at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:438)
                at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
                at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:604)
                at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:436)
                at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
                at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:484)
                at com.intellij.ide.IdeEventQueue.pumpEventsForHierarchy(IdeEventQueue.java:945)
                at com.intellij.openapi.progress.util.ProgressWindow.lambda$startBlocking$4(ProgressWindow.java:211)
                at com.intellij.openapi.application.impl.ApplicationImpl.runUnlockingIntendedWrite(ApplicationImpl.java:907)
                at com.intellij.openapi.progress.util.ProgressWindow.startBlocking(ProgressWindow.java:206)
                at com.intellij.openapi.progress.impl.ProgressRunner.lambda$execFromEDT$6(ProgressRunner.java:329)
                at java.base/java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:757)
                at java.base/java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:735)
                at java.base/java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2182)
                at com.intellij.openapi.progress.impl.ProgressRunner.execFromEDT(ProgressRunner.java:326)
                at com.intellij.openapi.progress.impl.ProgressRunner.submit(ProgressRunner.java:267)
                at com.intellij.openapi.progress.impl.ProgressRunner.submitAndGet(ProgressRunner.java:193)
                at com.intellij.openapi.project.impl.ProjectUiFrameAllocator.run(ProjectFrameAllocator.kt:117)
                at com.intellij.openapi.project.impl.ProjectManagerExImpl.doOpenAsync(ProjectManagerExImpl.kt:127)
                at com.intellij.openapi.project.impl.ProjectManagerExImpl.openProjectAsync(ProjectManagerExImpl.kt:114)
                at com.intellij.ide.RecentProjectsManagerBase.openProject(RecentProjectsManagerBase.kt:332)
                at com.intellij.openapi.wm.impl.welcomeScreen.recentProjects.RecentProjectItem.openProject(RecentProjectTreeItem.kt:84)
                at com.intellij.openapi.wm.impl.welcomeScreen.recentProjects.RecentProjectFilteringTree$Companion.activateItem(RecentProjectFilteringTree.kt:654)
                at com.intellij.openapi.wm.impl.welcomeScreen.recentProjects.RecentProjectFilteringTree$Companion.access$activateItem(RecentProjectFilteringTree.kt:633)
                at com.intellij.openapi.wm.impl.welcomeScreen.recentProjects.RecentProjectFilteringTree$ProjectActionMouseListener.mousePressed(RecentProjectFilteringTree.kt:255)
                at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:288)
                at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:287)
                at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:287)
                at java.desktop/java.awt.Component.processMouseEvent(Component.java:6645)
                at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3392)
                at com.intellij.ui.treeStructure.Tree.processMouseEvent(Tree.java:422)
                at java.desktop/java.awt.Component.processEvent(Component.java:6413)
                at java.desktop/java.awt.Container.processEvent(Container.java:2266)
                at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5022)
                at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
                at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
                at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
                at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4572)
                at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
                at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
                at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2802)
                at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
                at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:781)
                at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
                at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
                at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
                at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
                at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
                at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:754)
                at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:752)
                at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
                at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
                at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:751)
                at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:898)
                at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:820)
                at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:743)
                at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:439)
                at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:791)
                at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:438)
                at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
                at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:604)
                at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:436)
                at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
                at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:484)
                at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
                at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
                at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
                at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
                at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
                at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
Caused by: java.lang.IllegalAccessException: no such constructor: CompareDependencies.<init>()void/newInvokeSpecial
                at java.base/java.lang.invoke.MemberName.makeAccessException(MemberName.java:972)
                at java.base/java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1117)
                at java.base/java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:3649)
                at java.base/java.lang.invoke.MethodHandles$Lookup.findConstructor(MethodHandles.java:2750)
                at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:844)
                ... 128 more
Caused by: java.lang.NoClassDefFoundError: com/intellij/openapi/diff/DiffContent
                at java.base/java.lang.invoke.MethodHandleNatives.resolve(Native Method)
                at java.base/java.lang.invoke.MemberName$Factory.resolve(MemberName.java:1085)
                at java.base/java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1114)
                ... 131 more
Caused by: java.lang.ClassNotFoundException: com.intellij.openapi.diff.DiffContent PluginClassLoader(plugin=PluginDescriptor(name=Maven Dependency Manager, id=Maven Dependency Manager, descriptorPath=plugin.xml, path=~/Library/Application Support/JetBrains/IntelliJIdea2022.2/plugins/MavenDependencyPlugin, version=1.02, package=null, isBundled=false), packagePrefix=null, instanceId=194, state=active)
                at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:214)
                at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
                ... 134 more

**Comment by mikereiche** [comment]
The spring-data-mongodb repository has the same issue.

**Comment by mikereiche** [comment]
A simpler work-around is to right-click on the pom.xml of a sub-module, then Maven -> Ignore Project, then again right-click Maven -> Unignore Project.

**Comment by mikereiche** [comment]
2022-10-05 14:17:53,269 [  11803]   INFO - #o.j.i.maven - [maven import] applying models to workspace model took 11ms
2022-10-05 14:17:53,270 [  11804] SEVERE - #c.i.o.a.i.ApplicationImpl - Unable to find module entity for Module: 'spring-data-couchbase'
java.lang.IllegalStateException: Unable to find module entity for Module: 'spring-data-couchbase'
        at com.intellij.workspaceModel.ide.impl.legacyBridge.module.ModifiableModuleModelBridgeImpl.renameModule(ModifiableModuleModelBridgeImpl.kt:276)
        at org.jetbrains.idea.maven.importing.ModuleModelProxyWrapper.renameModule(ModuleModelProxyImpl.kt:53)
        at org.jetbrains.idea.maven.importing.MavenProjectImporterImpl.ensureModuleCreated(MavenProjectImporterImpl.java:384)
        at org.jetbrains.idea.maven.importing.MavenProjectImporterImpl.importModules(MavenProjectImporterImpl.java:341)
        at org.jetbrains.idea.maven.importing.MavenProjectImporterImpl.importProject(MavenProjectImporterImpl.java:95)
        at org.jetbrains.idea.maven.importing.MavenProjectImporter$Companion$createImporter$1.importProject(MavenProjectImporter.kt:36)
        at org.jetbrains.idea.maven.project.MavenProjectsManager.lambda$importProjects$24(MavenProjectsManager.java:1324)
        at org.jetbrains.idea.maven.project.MavenProjectsManager$10.run(MavenProjectsManager.java:1339)
        at org.jetbrains.idea.maven.utils.MavenUtil.lambda$runInBackground$11(MavenUtil.java:611)
        at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:297)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
        at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
        at java.base/java.lang.Thread.run(Thread.java:833)
2022-10-05 14:17:53,272 [  11806] SEVERE - #c.i.o.a.i.ApplicationImpl - IntelliJ IDEA 2022.2.2  Build #IU-222.4167.29
2022-10-05 14:17:53,272 [  11806] SEVERE - #c.i.o.a.i.ApplicationImpl - JDK: 17.0.4; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2022-10-05 14:17:53,272 [  11806] SEVERE - #c.i.o.a.i.ApplicationImpl - OS: Mac OS X
2022-10-05 14:17:55,229 [  13763]   INFO - #c.i.o.e.s.p.m.ReprocessContentRootDataActivity - Ignored reprocess of content root data service for new projects
2022-10-05 14:17:55,238 [  13772]   INFO - #o.j.j.b.i.CompilerReferenceIndex - backward reference index version doesn't exist

**Comment by mikereiche** [comment]
went back to single module
