### ISSUE TITLE
TransactionSystemUnambiguousException wrapping exceptions thrown in a @Transactional method

### ISSUE THREAD

**Issue by PRodrigues-eb** [spring-projects/spring-data-couchbase#1578]
We noticed that if we throw an exception inside a `@Transactional `method it is wrapped by a `TransactionSystemUnambiguousException`. Is that behavior desired?

For example, we have a code like the following inside a `@Transactional `method:

```
        Outbox foundOutboxMessage = outboxRepository.findByUuidAcquiringWriteLock(outboxMessage.getUuid())
                .orElseThrow(() -> {
                    String errorMessage = "Couldn't find outbox with UUID '" + outboxMessage.getUuid()
                            + "'. This could happen if previous transaction for storing outbox isn't committed yet.";
                    return new NotFoundException(errorMessage);
                });
```

In the case of the NotFoundException be thrown, the `@Transactional `method will throw an `TransactionSystemUnambiguousException` with the `NotFoundException` as the cause.

Stack trace:

```
org.springframework.data.couchbase.transaction.error.TransactionSystemUnambiguousException: Transaction has failed with cause 'com.employbridge.account.manager.exception.NotFoundException: Couldn't find outbox with UUID '37ff6998-c7df-483c-98c0-b2e0b67cf860'. This could happen if previous transaction for storing outbox isn't committed yet.'
	at org.springframework.data.couchbase.transaction.CouchbaseCallbackTransactionManager.convert(CouchbaseCallbackTransactionManager.java:139)
	at org.springframework.data.couchbase.transaction.CouchbaseCallbackTransactionManager.executeNewTransaction(CouchbaseCallbackTransactionManager.java:130)
	at org.springframework.data.couchbase.transaction.CouchbaseCallbackTransactionManager.execute(CouchbaseCallbackTransactionManager.java:83)
	at org.springframework.data.couchbase.transaction.CouchbaseTransactionInterceptor.invokeWithinTransaction(CouchbaseTransactionInterceptor.java:81)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:755)
```

**Comment by mikereiche** [comment]
Yes. This is the expected and desired behavior. It signifies that the application does not need to do anything to rollback the transaction.  To see usage of transactions in spring-data-couchbase there are over 400 test cases in  

```
 git clone git@github.com:spring-projects/spring-data-couchbase.git
 cd ./spring-data-couchbase/spring-data-couchbase/src/test/java/org/springframework/data/couchbase/transactions

```
