### ISSUE TITLE
Crud repository query methods are not working with List<Enum> as a parameter.

### ISSUE THREAD

**Issue by jakubszybisty** [spring-projects/spring-data-couchbase#1855]
Hello,
I am trying to write a method which accepts List containing enum as a parameter in an interface extending ListCrudRepository<T, UUID>

`
T findByEnumType(List<EnumType> enums)
`

however, in the result exception is thrown:
```
Caused by: com.couchbase.client.core.error.InvalidArgumentException: Unsupported type for JSON value: class com.xxx.EnumType
	at com.couchbase.client.core.error.InvalidArgumentException.fromMessage(InvalidArgumentException.java:28)
	at com.couchbase.client.java.json.JsonValue.coerce(JsonValue.java:94)
	at com.couchbase.client.java.json.JsonArray.add(JsonArray.java:178)

```

**Comment by mikereiche** [comment]
I just fixed this - it should be in 5.1.5 which was just.  Can you please check that?   https://github.com/spring-projects/spring-data-couchbase/issues/1837

**Comment by jakubszybisty** [comment]
There's a bigger stacktrace:
```
```
Caused by: com.couchbase.client.core.error.InvalidArgumentException: Unsupported type for JSON value: class com.EventType
	at com.couchbase.client.core.error.InvalidArgumentException.fromMessage(InvalidArgumentException.java:28)
	at com.couchbase.client.java.json.JsonValue.coerce(JsonValue.java:94)
	at com.couchbase.client.java.json.JsonArray.add(JsonArray.java:178)
	at org.springframework.data.couchbase.core.query.QueryCriteria.addAsCollection(QueryCriteria.java:650)
	at org.springframework.data.couchbase.core.query.QueryCriteria.maybeWrapValue(QueryCriteria.java:598)
	at org.springframework.data.couchbase.core.query.QueryCriteria.exportSingle(QueryCriteria.java:565)
	at org.springframework.data.couchbase.core.query.QueryCriteria.export(QueryCriteria.java:526)
	at org.springframework.data.couchbase.core.query.Query.appendWhere(Query.java:279)
	at org.springframework.data.couchbase.core.query.Query.toN1qlSelectString(Query.java:359)
	at org.springframework.data.couchbase.core.ReactiveFindByQueryOperationSupport$ReactiveFindByQuerySupport.assembleEntityQuery(ReactiveFindByQueryOperationSupport.java:281)
	at org.springframework.data.couchbase.core.ReactiveFindByQueryOperationSupport$ReactiveFindByQuerySupport.all(ReactiveFindByQueryOperationSupport.java:182)
	at org.springframework.data.couchbase.core.ExecutableFindByQueryOperationSupport$ExecutableFindByQuerySupport.all(ExecutableFindByQueryOperationSupport.java:95)
	at org.springframework.data.couchbase.repository.query.AbstractCouchbaseQuery.lambda$getExecutionToWrap$1(AbstractCouchbaseQuery.java:124)
	at org.springframework.data.couchbase.repository.query.CouchbaseQueryExecution$ResultProcessingExecution.execute(CouchbaseQueryExecution.java:84)
	at org.springframework.data.couchbase.repository.query.AbstractCouchbaseQuery.doExecute(AbstractCouchbaseQuery.java:93)
	at org.springframework.data.couchbase.repository.query.AbstractCouchbaseQueryBase.execute(AbstractCouchbaseQueryBase.java:132)
	at org.springframework.data.couchbase.repository.query.AbstractCouchbaseQueryBase.execute(AbstractCouchbaseQueryBase.java:113)
	at org.springframework.data.repository.core.support.RepositoryMethodInvoker.doInvoke(RepositoryMethodInvoker.java:136)
	at org.springframework.data.repository.core.support.RepositoryMethodInvoker.invoke(RepositoryMethodInvoker.java:120)
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.doInvoke(QueryExecutorMethodInterceptor.java:164)
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.invoke(QueryExecutorMethodInterceptor.java:143)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:72)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.data.couchbase.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:145)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:244)
	at com.findByEventTypes(Unknown Source)
	at com.findConfigsByEventType(XXXREPOsitory.java:32)
```

**Comment by mikereiche** [comment]
Yes. I never actually fixed it. Sorry for sending you down that path.

> I am not overriding any couchbase configuration. 

That's the issue.   Since you don't override it, you get one provided for you  ...  the couchbaseCustomConversions created in CouchbaseDataConfiguration does not have the Enum converters (I'll need to work with spring-boot-autoconfigure to fix that).  The work-around in #1837 is to have the @Configuration class extend AbstractCouchbaseConfiguration (see the last post in #1837).

**Comment by jakubszybisty** [comment]
Alright, thank you! Is there a chance that the autoconfiguration fix will come anywhere soon?
