### ISSUE TITLE
Native Build Fails When Couchbase Auditing is Enabled

### ISSUE THREAD

**Issue by korkutkose** [spring-projects/spring-data-couchbase#1884]
Hi,
On latest spring-boot version, when applied Couchbase auditing according to [this](https://docs.spring.io/spring-data/couchbase/docs/5.1.3/reference/html/#auditing) article and tried build a native image image generation's failed with below trace. 
When we commented out @EnableCouchbaseAuditing in the configuration class and proceeded with image generation image's been successfully built without any exceptions. 
Is there any more configuration for native build generation that we should follow for auditing support?
```
2023-12-25T09:52:38.887+03:00  INFO 3602 --- [tams-slot-planner] [           main] [                                                 ] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 10 ms. Found 2 JPA repository interfaces.
Exception in thread "main" java.lang.IllegalStateException: No constructor or factory method candidate found for Root bean: class [org.springframework.data.couchbase.core.mapping.event.AuditingEventListener]; scope=singleton; abstract=false; lazyInit=null; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodNames=null; destroyMethodNames=null and argument types [org.springframework.beans.factory.ObjectFactory<java.lang.Object>]
	at org.springframework.beans.factory.support.ConstructorResolver.resolveConstructorOrFactoryMethod(ConstructorResolver.java:994)
	at org.springframework.beans.factory.support.RegisteredBean.resolveConstructorOrFactoryMethod(RegisteredBean.java:212)
	at org.springframework.util.function.SingletonSupplier.get(SingletonSupplier.java:106)
	at org.springframework.beans.factory.aot.DefaultBeanRegistrationCodeFragments.getTarget(DefaultBeanRegistrationCodeFragments.java:80)
	at org.springframework.beans.factory.aot.BeanDefinitionMethodGenerator.generateBeanDefinitionMethod(BeanDefinitionMethodGenerator.java:85)
	at org.springframework.beans.factory.aot.BeanRegistrationsAotContribution.lambda$generateRegisterBeanDefinitionsMethod$2(BeanRegistrationsAotContribution.java:90)
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
	at org.springframework.beans.factory.aot.BeanRegistrationsAotContribution.generateRegisterBeanDefinitionsMethod(BeanRegistrationsAotContribution.java:88)
	at org.springframework.beans.factory.aot.BeanRegistrationsAotContribution.lambda$applyTo$1(BeanRegistrationsAotContribution.java:73)
	at org.springframework.aot.generate.GeneratedMethod.<init>(GeneratedMethod.java:54)
	at org.springframework.aot.generate.GeneratedMethods.add(GeneratedMethods.java:112)
	at org.springframework.aot.generate.GeneratedMethods.add(GeneratedMethods.java:89)
	at org.springframework.beans.factory.aot.BeanRegistrationsAotContribution.applyTo(BeanRegistrationsAotContribution.java:72)
	at org.springframework.context.aot.BeanFactoryInitializationAotContributions.applyTo(BeanFactoryInitializationAotContributions.java:78)
	at org.springframework.context.aot.ApplicationContextAotGenerator.lambda$processAheadOfTime$0(ApplicationContextAotGenerator.java:58)
	at org.springframework.context.aot.ApplicationContextAotGenerator.withCglibClassHandler(ApplicationContextAotGenerator.java:67)
	at org.springframework.context.aot.ApplicationContextAotGenerator.processAheadOfTime(ApplicationContextAotGenerator.java:53)
	at org.springframework.context.aot.ContextAotProcessor.performAotProcessing(ContextAotProcessor.java:106)
	at org.springframework.context.aot.ContextAotProcessor.doProcess(ContextAotProcessor.java:84)
	at org.springframework.context.aot.ContextAotProcessor.doProcess(ContextAotProcessor.java:49)
	at org.springframework.context.aot.AbstractAotProcessor.process(AbstractAotProcessor.java:82)
	at org.springframework.boot.SpringApplicationAotProcessor.main(SpringApplicationAotProcessor.java:80)
```

```
@Slf4j
@Configuration
@EnableCouchbaseRepositories(basePackages = "com.acme.nosql")
@EnableCouchbaseAuditing(auditorAwareRef = "auditorAware")
public class CouchbaseConfig extends AbstractCouchbaseConfiguration {
 ...other attributes
  @Bean
  public NativeAuditorAware auditorAware() {
    return new NativeAuditorAware();
  }
}
```

```
public class NativeAuditorAware implements AuditorAware<String> {

  @Override
  public Optional<String> getCurrentAuditor() {
    String user = ContextHolder.get() != null ? ContextHolder.get().getUser() : null;
    if (StringUtils.isNotEmpty(user)) {
      return Optional.of(user);
    }
    return Optional.of("unknown");
  }
}
```

**Comment by mikereiche** [comment]
It should work. We build and test auditing in the integration tests. Can you attach your build dependencies file - pom.xml,  build.gradle, whatever.

**Comment by korkutkose** [comment]
Hey, sorry for the delay @mikereiche. 
I'll do better. Here's the minimal replicator project for the issue. 
[https://github.com/korkutkose/couchbase-demo](korkutkose/couchbase-demo)

**Comment by mikereiche** [comment]
Thanks. I can reproduce it. I'll investigate.

**Comment by cabbonizio** [comment]
I just upgraded to Spring Boot 3.2.3 and first time I am seeing this error.  I have not seen this error prior to this version of spring boot

**Comment by cabbonizio** [comment]
I am thinking had something to do with this commit:

https://github.com/spring-projects/spring-data-couchbase/commit/86713c527c0e6cf5a3fde6fa44f119cc719c9bb9

**Comment by mikereiche** [comment]
@cabbonizio - according to my note above, adding a constructor to AuditEvenListener solves the issue.  Not sure why I haven't done that yet.

**Comment by cabbonizio** [comment]
Ok, got it now I just saw your commit.   Thanks for the response.  For now, I may upgrade to Spring Boot 3.2.3 but downgrade SDC to 5.2.2 for now.
