### ISSUE TITLE
DynamicProxyable works only with non-primitive arguments

### ISSUE THREAD

**Issue by mikereiche** [spring-projects/spring-data-couchbase#1965]
see https://www.couchbase.com/forums/t/reactive-dynamicproxyable-is-not-working/39163

Issue is in FindMethod
https://github.com/spring-projects/spring-data-couchbase/blob/10f71c9db4aad582dc2efd5524cd34621b9c9b54/src/main/java/org/springframework/data/couchbase/repository/support/FindMethod.java#L124-L128

**Comment by mikereiche** [comment]
Could do something like this for int/Integer, but I'm hoping to find something that is less of a hack.

                if(params[j] == int.class && parameterTypes[j] == Integer.class )
                    continue;

**Comment by mikereiche** [comment]
//  primitive types are : int, byte, short, long, float, double, boolean, and char.
         // but only int, long, double and boolean are supported...
	Flux<Airport> findAll(int iint, long llong, double ddouble, boolean bboolean);
	
	
```
	com.couchbase.client.core.error.InvalidArgumentException: Unsupported type for JSON value: class java.lang.Character
	at com.couchbase.client.core.error.InvalidArgumentException.fromMessage(InvalidArgumentException.java:28)
	at com.couchbase.client.java.json.JsonValue.coerce(JsonValue.java:97)
	at com.couchbase.client.java.json.JsonArray.add(JsonArray.java:207)
	at org.springframework.data.couchbase.repository.query.StringBasedN1qlQueryParser.putPositionalValue(StringBasedN1qlQueryParser.java:554)
```
